services:

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: mysql_estimator_db
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_estimator:/var/lib/mysql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    container_name: estimator_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/estimator
      SPRING_DATASOURCE_USERNAME: bestuser
      SPRING_DATASOURCE_PASSWORD: bestuser
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_estimator:

networks:
  app-network:
    driver: bridge

